#!/usr/bin/env ansible-playbook
---
- name: Start up an alpine containertools image
  hosts: localhost


  tasks:
    - name: Install docker module
      pip:
        name: docker
    - name: Start up a docker container
      docker_container:
        name: client
        image: raesene/alpine-containertools
        networks:
          - name: kind
    - name: add the host
      add_host: name=client

- name: install Python in the cluster
  hosts: client
  connection: docker
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - import_tasks: ./ansible_tasks/install_python3_alpine_raw.yml
  
- name: Configure the demo client
  hosts: client
  connection: docker
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
  - name: Set the bash prompt
    copy:
      src: client_files/clientbashrc
      dest: /root/.bashrc